# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the build output from the host to the container
COPY build/libs/*.jar Task-management-1.0-SNAPSHOT.jar

# Expose the port that the application will run on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "Task-management-1.0-SNAPSHOT.jar"]