server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://bitxf6izhhipgjfwhak9-mysql.services.clever-cloud.com:3306/bitxf6izhhipgjfwhak9
    username: ukjlqbjb2oeiizk5
    password: dahoQbKZPiEgwOvOUQFS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none


